# Generated by Django 6.0.1 on 2026-01-30 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowchartSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Codul de Procedură Penală al Republicii Moldova', max_length=200, verbose_name='Titlu')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Subtitlu')),
                ('default_zoom', models.FloatField(default=1.0, verbose_name='Zoom implicit')),
                ('min_zoom', models.FloatField(default=0.1, verbose_name='Zoom minim')),
                ('max_zoom', models.FloatField(default=2.0, verbose_name='Zoom maxim')),
                ('background_color', models.CharField(default='#f8fafc', max_length=7, verbose_name='Culoare fundal')),
                ('node_border_radius', models.PositiveIntegerField(default=8, verbose_name='Rotunjire noduri (px)')),
                ('export_watermark', models.CharField(default='penitadreptului.md', max_length=200, verbose_name='Watermark export')),
            ],
            options={
                'verbose_name': 'Setări diagramă',
                'verbose_name_plural': 'Setări diagramă',
            },
        ),
        migrations.CreateModel(
            name='LegalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=20, verbose_name='Numărul articolului')),
                ('title', models.CharField(max_length=500, verbose_name='Titlu')),
                ('content', models.TextField(verbose_name='Conținut')),
                ('content_ru', models.TextField(blank=True, verbose_name='Conținut (RU)')),
                ('chapter', models.CharField(blank=True, max_length=200, verbose_name='Capitol')),
                ('external_url', models.URLField(blank=True, help_text='Link către versiunea oficială a articolului (legis.md)', verbose_name='Link extern')),
            ],
            options={
                'verbose_name': 'Articol CPP',
                'verbose_name_plural': 'Articole CPP',
                'ordering': ['article_number'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Denumire')),
                ('name_ru', models.CharField(blank=True, max_length=200, verbose_name='Denumire (RU)')),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('color', models.CharField(default='#3b82f6', help_text='Cod HEX pentru culoarea nodurilor din această categorie', max_length=7, verbose_name='Culoare')),
            ],
            options={
                'verbose_name': 'Categorie procedură',
                'verbose_name_plural': 'Categorii proceduri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titlu')),
                ('title_ru', models.CharField(blank=True, max_length=300, verbose_name='Titlu (RU)')),
                ('short_title', models.CharField(help_text='Afișat pe nodurile mici', max_length=100, verbose_name='Titlu scurt')),
                ('description', models.TextField(blank=True, verbose_name='Descriere')),
                ('description_ru', models.TextField(blank=True, verbose_name='Descriere (RU)')),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('end', 'Sfârșit'), ('process', 'Proces'), ('decision', 'Decizie'), ('document', 'Document'), ('subprocess', 'Subproces')], default='process', max_length=20, verbose_name='Tip nod')),
                ('position_x', models.IntegerField(default=0, verbose_name='Poziția X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Poziția Y')),
                ('deadline_days', models.PositiveIntegerField(blank=True, help_text='Termenul legal în zile', null=True, verbose_name='Termen (zile)')),
                ('deadline_note', models.CharField(blank=True, help_text="Ex: '15 zile de la comunicare'", max_length=200, verbose_name='Notă termen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_keywords', models.TextField(blank=True, help_text='Cuvinte cheie pentru căutare, separate prin virgulă', verbose_name='Cuvinte cheie')),
                ('articles', models.ManyToManyField(blank=True, related_name='stages', to='flowchart.legalarticle', verbose_name='Articole CPP')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='flowchart.procedurecategory', verbose_name='Categorie')),
                ('parent', models.ForeignKey(blank=True, help_text='Pentru noduri imbricate (expand/collapse)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='flowchart.procedurestage', verbose_name='Etapa părinte')),
            ],
            options={
                'verbose_name': 'Etapă procedură',
                'verbose_name_plural': 'Etape procedură',
                'ordering': ['category__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StageConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='Etichetă')),
                ('edge_type', models.CharField(choices=[('default', 'Implicit'), ('success', 'Succes'), ('failure', 'Eșec'), ('conditional', 'Condiționat'), ('optional', 'Opțional')], default='default', max_length=20, verbose_name='Tip conexiune')),
                ('condition', models.CharField(blank=True, help_text="Ex: 'Da', 'Nu', 'În termen'", max_length=200, verbose_name='Condiție')),
                ('animated', models.BooleanField(default=False, verbose_name='Animat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='flowchart.procedurestage', verbose_name='De la')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='flowchart.procedurestage', verbose_name='Către')),
            ],
            options={
                'verbose_name': 'Conexiune',
                'verbose_name_plural': 'Conexiuni',
                'ordering': ['order'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
