# Generated by Django 6.0.1 on 2026-01-30 10:52

from django.db import migrations, models


def update_existing_settings(apps, schema_editor):
    FlowchartSettings = apps.get_model('flowchart', 'FlowchartSettings')
    FlowchartSettings.objects.filter(default_zoom=1.0).update(default_zoom=1.5)


def revert_settings(apps, schema_editor):
    FlowchartSettings = apps.get_model('flowchart', 'FlowchartSettings')
    FlowchartSettings.objects.filter(default_zoom=1.5).update(default_zoom=1.0)


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchartsettings',
            name='default_zoom',
            field=models.FloatField(default=1.5, verbose_name='Zoom implicit'),
        ),
        migrations.RunPython(update_existing_settings, revert_settings),
    ]
